import { absoluteUrl } from './site';

/**
 * Open Graph image metadata helpers.
 *
 * The OG cards are generated by the `*.png` route handlers under `app/` (e.g.
 * `/og-home.png`, `/og-default.png`, `/blog/[slug]/og.png`). These helpers build
 * the matching `metadata.openGraph.images` / `metadata.twitter.images` entries
 * so every page references a real `.png` URL and declares `og:image:type`.
 *
 * Kept free of any React/satori imports so importing it into page metadata does
 * not pull the image-template module into page bundles.
 */

/** Standard OG card dimensions (1200×630), matching `OG_SIZE` in `lib/og/template`. */
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/**
 * A fully-specified Open Graph image descriptor. Assignable to both
 * `metadata.openGraph.images` and (via `.url`) `metadata.twitter.images`.
 */
export interface OgImage {
  url: string;
  width: number;
  height: number;
  type: 'image/png';
  alt: string;
}

/**
 * Build an `openGraph.images` entry for one of our PNG card routes.
 * @param path - Absolute-from-root path to the card (e.g. `/og-home.png`).
 * @param alt - Accessible description of the card.
 */
export function ogImage(path: string, alt: string): OgImage {
  return {
    url: absoluteUrl(path),
    width: OG_IMAGE_WIDTH,
    height: OG_IMAGE_HEIGHT,
    type: 'image/png',
    alt,
  };
}

/** Alt text for the site-wide default card. */
export const DEFAULT_OG_ALT = 'Agent Relay — Headless Slack for Agents';

/** The site-wide default card, served by `app/og-default.png/route.tsx`. */
export function defaultOgImage(): OgImage {
  return ogImage('/og-default.png', DEFAULT_OG_ALT);
}
