/**
 * Canonical Lead-1 qualification surface.
 *
 * The CLI source currently exposes 125 public executable operations. Cloud's
 * 30-operation subtree is owned by the Cloud qualification lane, leaving these
 * 95 public non-Cloud operations. Hidden compatibility aliases are audited
 * separately and must never be used to pad this list.
 */
export const FLEET_QUALIFICATION_OPERATIONS = Object.freeze([
  'node up',
  'node down',
  'node status',
  'node metrics',
  'node deadletters',
  'node redeliver',
  'node tail',
  'node agent list',
  'node agent spawn',
  'node agent new',
  'node agent release',
  'node agent set-model',
  'node agent attach',
  'node agent message flush',
  'node agent message hold',
  'node agent message auto',
  'node workflow run',
  'node workflow logs',
  'node workflow sync',
  'status',
  'version',
  'update',
  'uninstall',
  'telemetry',
  'mcp',
  'reflex on',
  'reflex off',
  'reflex status',
  'session replay',
  'fleet agent list',
  'fleet config',
  'fleet disable',
  'fleet enable',
  'fleet inherit',
  'fleet nodes',
  'fleet release',
  'fleet spawn',
  'fleet status',
  'workspace create',
  'workspace active',
  'workspace list',
  'workspace set_key',
  'workspace join',
  'workspace key',
  'workspace switch',
  'workspace restore',
  'workspace rebind',
  'observer',
  'observer list',
  'observer revoke',
  'agent register',
  'agent rotate',
  'agent list',
  'agent add',
  'agent remove',
  'agent me',
  'agent presence',
  'channel create',
  'channel list',
  'channel join',
  'channel leave',
  'channel invite',
  'channel set_topic',
  'channel archive',
  'message post',
  'message list',
  'message reply',
  'message get_thread',
  'message search',
  'message dm send',
  'message dm list',
  'message dm send_group',
  'message reaction add',
  'message reaction remove',
  'message inbox check',
  'message inbox mark_read',
  'message inbox get_readers',
  'message file upload',
  'integration subscribe',
  'integration unsubscribe',
  'integration webhook create',
  'integration webhook list',
  'integration webhook delete',
  'integration webhook trigger',
  'integration webhook create-inbound',
  'integration webhook list-inbound',
  'integration webhook delete-inbound',
  'integration subscription create',
  'integration subscription list',
  'integration subscription get',
  'integration subscription delete',
  'capabilities register',
  'capabilities list',
  'capabilities delete',
  'skills add',
]);

export const HIDDEN_COMPATIBILITY_SURFACES = Object.freeze([
  'local up',
  'local down',
  'local status',
  'local metrics',
  'local deadletters',
  'local redeliver',
  'local tail',
  'local agent list',
  'local agent spawn',
  'local agent new',
  'local agent release',
  'local agent set-model',
  'local agent attach',
  'local agent message flush',
  'local agent message hold',
  'local agent message auto',
  'local run',
  'local logs',
  'local sync',
  'fleet serve',
]);

if (FLEET_QUALIFICATION_OPERATIONS.length !== 95) {
  throw new Error(
    `Fleet qualification inventory drifted: expected 95, found ${FLEET_QUALIFICATION_OPERATIONS.length}`
  );
}
