/**
 * On-demand package tree for the mounted product SDKs.
 *
 * The npm distribution needs none of this: `@relayfile/sdk`, `@relayflows/sdk`
 * and `ai-hist` are ordinary dependencies of `agent-relay`, so
 * `import('@relayfile/sdk/relay-cli')` resolves and nothing here ever runs.
 *
 * The compiled standalone binary is the problem (#1795). It is one file with no
 * node_modules, so every mounted group failed with MODULE_NOT_FOUND — reported
 * as "not installed", in a distribution where installing cannot help. Bundling
 * the SDKs does not fix it, and was tried:
 *
 *   - `@relayfile/sdk/relay-cli` locates and spawns a Go binary; exec needs a
 *     real path on disk, not a bundled module
 *   - `ai-hist` dlopens a native addon through a *variable* specifier, which no
 *     bundler can see
 *   - all three read data files relative to `import.meta.url`, which relocates
 *     into Bun's `/$bunfs/root` once compiled
 *
 * So instead of pulling the packages into the binary, the binary puts them back
 * on disk: a real `npm install` of the version pinned in
 * `packages/cli/package.json`, under `~/.agentworkforce/relay/surfaces`, and the
 * surface is imported from there. Real files satisfy dlopen, exec,
 * `import.meta.url` and variable specifiers at once.
 */

import { execFile, spawn } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';

import type { RelayCliIo, RelayCliSurface } from '@agent-relay/cli-surface';

import { redactCredentialValues } from '@agent-relay/cloud/redact';

import { describeError } from './describe-error.js';
import { isBundledBunEntrypointPath } from './agent-relay-mcp-command.js';
import { isBunRuntime } from './node-definition-loader.js';

const execFileAsync = promisify(execFile);

/** How long a single provisioning install may take before it is abandoned. */
export const INSTALL_TIMEOUT_MS = 10 * 60 * 1000;

/** Largest npm output we will buffer while waiting for the install. */
const INSTALL_MAX_BUFFER = 16 * 1024 * 1024;

/**
 * Name of the generated module that performs the import.
 *
 * It has to live *inside* the provisioned directory. A bare specifier resolves
 * against the `node_modules` directories above the importing module, so an
 * `import()` written in the CLI's own source could never see this tree no
 * matter where it is; one written next to it sees nothing else.
 */

const RUNNER_FILENAME = 'run-surface.mjs';

const RUNNER_SOURCE = `// Generated by agent-relay. Do not edit.
//
// Entry point for a child process that runs one mounted product surface out
// of the node_modules beside this file.
//
// Why a child process rather than importing into the CLI: inside the compiled
// standalone binary, Bun cannot resolve bare specifiers from a tree it loaded
// by absolute path. Resolving the surface entry point by hand gets as far as
// the entry point; its own imports then fail the same way, and there is no
// bottom to that. NODE_PATH does not change it. Running under the node that
// performed the install sidesteps module resolution entirely, and costs one
// process per invocation.
//
// Two modes, because the host renders help from the declared command tree and
// must not forward it — help has to say agent-relay, not the product's name:
//
//   describe        print {id, version, contract, commands} as JSON
//   run [argv...]   run the surface, streaming its output
import process from 'node:process';

const [mode, specifier, ...argv] = process.argv.slice(2);

const module = await import(specifier);
if (typeof module.createRelayCliSurface !== 'function') {
  process.stderr.write(specifier + ' does not export createRelayCliSurface()\\n');
  process.exit(1);
}
const surface = await module.createRelayCliSurface();

if (mode === 'describe') {
  process.stdout.write(
    JSON.stringify({
      id: surface.id,
      version: surface.version,
      contract: surface.contract,
      commands: surface.commands,
    })
  );
  process.exit(0);
}

// stdout and stderr are written straight through: the host pipes them into
// its own io sink, and chunks stay bytes so a binary payload survives.
const code = await surface.run(argv, {
  stdout: (chunk) => process.stdout.write(chunk),
  stderr: (chunk) => process.stderr.write(chunk),
});
process.exit(typeof code === 'number' ? code : 0);
`;

/** A product SDK to provision, named exactly as the CLI manifest pins it. */
export interface SurfacePackage {
  /** Bare package name, e.g. `@relayfile/sdk`. */
  name: string;
  /** Version range copied from `packages/cli/package.json`, e.g. `^0.10.64`. */
  range: string;
}

/** Injectable seams; the defaults are the real store on the real filesystem. */
export interface SurfaceStoreDependencies {
  /** Directory holding every provisioned tree. */
  root: string;
  /** Install `pkg` into an already-created `directory`. */
  install: (pkg: SurfacePackage, directory: string) => Promise<void>;
  /** Progress and failure notices. Never stdout: that is the caller's data. */
  notify: (line: string) => void;
}

/** Error code carried by every failure this module reports to the mount. */
export const PROVISION_ERROR_CODE = 'ERR_RELAY_SURFACE_PROVISION';

/**
 * A provisioning failure with an operator-facing message.
 *
 * Tagged with a code so `describeLoadFailure` can print {@link Error.message}
 * verbatim. The message already names the package, the directory and the fix;
 * wrapping it in "Could not load … :" or letting a stack through would bury
 * that.
 */
export class SurfaceProvisionError extends Error {
  readonly code = PROVISION_ERROR_CODE;

  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'SurfaceProvisionError';
  }
}

/** `~/.agentworkforce/relay/surfaces`, or the configured data directory. */
export function defaultSurfaceStoreRoot(): string {
  const dataDir = process.env['AGENT_RELAY_DATA_DIR'] || path.join(os.homedir(), '.agentworkforce/relay');
  return path.join(dataDir, 'surfaces');
}

/**
 * Whether this process is the compiled standalone binary.
 *
 * Both halves matter. `isBunRuntime` alone is true for anyone running the CLI
 * under `bun`, where node_modules exists and provisioning would be pure waste;
 * the `/$bunfs/root` entrypoint is what distinguishes `bun build --compile`
 * output, which has no node_modules at all.
 */
export function isCompiledStandalone(argv: readonly string[] = process.argv): boolean {
  return isBunRuntime() && isBundledBunEntrypointPath(argv[1] ?? '');
}

/**
 * Where `pkg` is provisioned under `root`.
 *
 * Keyed by name *and* range, so upgrading the pin provisions a fresh tree
 * rather than reusing a stale one. The readable prefix is for whoever opens the
 * directory; the digest is what actually separates `^0.10.64` from `~0.10.64`,
 * which sanitizing alone collapses onto the same name.
 */
export function surfaceInstallPath(root: string, pkg: SurfacePackage): string {
  const digest = createHash('sha256').update(`${pkg.name}@${pkg.range}`).digest('hex').slice(0, 8);
  // `-` is deliberately not in the kept set: leaving it in makes `sdk-^0.10.64`
  // read as `sdk--0.10.64`, since the separator and the range operator are adjacent.
  const readable = `${pkg.name}-${pkg.range}`.replace(/[^A-Za-z0-9.]+/g, '-').replace(/^-+|-+$/g, '');
  return path.join(root, `${readable}-${digest}`);
}

/**
 * Provisioning runs already in flight, keyed by their destination.
 *
 * Two groups invoked in one process, or one group whose loader is retried,
 * must not start two npm installs of the same package. Cross-process races are
 * handled separately, by the atomic rename in {@link provisionOnce}.
 */
const inFlight = new Map<string, Promise<string>>();

function defaults(overrides: Partial<SurfaceStoreDependencies>): SurfaceStoreDependencies {
  return {
    root: overrides.root ?? defaultSurfaceStoreRoot(),
    install: overrides.install ?? npmInstall,
    notify: overrides.notify ?? ((line) => process.stderr.write(`${line}\n`)),
  };
}

/**
 * Ensure `pkg` is installed in the store and return the directory holding it.
 *
 * @param pkg - Package name and the range pinned by the CLI manifest.
 * @param overrides - Test seams for the store root, installer, and notices.
 * @returns Absolute path to a directory with `node_modules` and the loader.
 * @throws {SurfaceProvisionError} When the install cannot be completed, with a
 *   message naming the fix rather than a stack.
 */
export async function provisionSurfacePackage(
  pkg: SurfacePackage,
  overrides: Partial<SurfaceStoreDependencies> = {}
): Promise<string> {
  const deps = defaults(overrides);
  const target = surfaceInstallPath(deps.root, pkg);
  if (fs.existsSync(path.join(target, RUNNER_FILENAME))) return target;

  const existing = inFlight.get(target);
  if (existing) return existing;

  const run = provisionOnce(pkg, target, deps).finally(() => {
    inFlight.delete(target);
  });
  inFlight.set(target, run);
  return run;
}

/**
 * Install into a private staging directory, then publish it with one rename.
 *
 * The rename is what makes a concurrent second process safe: the destination
 * either does not exist or is a finished tree, never a half-written one, so a
 * reader can never import from an install that is still running. The loser of
 * the race discards its own work and adopts the winner's — both trees hold the
 * same pinned version, so there is nothing to reconcile.
 */
async function provisionOnce(
  pkg: SurfacePackage,
  target: string,
  deps: SurfaceStoreDependencies
): Promise<string> {
  const spec = `${pkg.name}@${pkg.range}`;
  fs.mkdirSync(deps.root, { recursive: true });
  // Unique per attempt, so two processes never write into the same staging
  // tree and npm never sees another install's partial node_modules.
  const staging = `${target}.staging-${process.pid}-${randomBytes(4).toString('hex')}`;
  fs.mkdirSync(staging, { recursive: true });

  try {
    // npm walks up from its cwd looking for a manifest; without this it would
    // find the user's project (or this repo) and install into that instead.
    fs.writeFileSync(
      path.join(staging, 'package.json'),
      `${JSON.stringify(
        {
          name: 'agent-relay-surface',
          version: '0.0.0',
          private: true,
          dependencies: { [pkg.name]: pkg.range },
        },
        null,
        2
      )}\n`
    );
    fs.writeFileSync(path.join(staging, RUNNER_FILENAME), RUNNER_SOURCE);

    // A silent multi-second npm install is indistinguishable from a hang, and
    // this one is minutes on a cold cache.
    deps.notify(
      `agent-relay: ${spec} is not bundled into the standalone binary; installing it now.\n` +
        `  -> ${target}\n` +
        `  This runs once per version. Later runs reuse it.`
    );

    const started = Date.now();
    try {
      await deps.install(pkg, staging);
    } catch (error) {
      throw new SurfaceProvisionError(
        `${spec} could not be installed into ${deps.root}.\n` +
          `${describeError(error)}\n` +
          `The standalone agent-relay binary installs the product SDKs on first use, ` +
          `so this needs \`npm\` on PATH and network access to the npm registry.\n` +
          `Retry when online, or install agent-relay from npm (\`npm i -g agent-relay\`), ` +
          `which ships ${pkg.name} directly.`,
        { cause: error }
      );
    }

    try {
      fs.renameSync(staging, target);
    } catch (error) {
      // Another process published the same version between our existence check
      // and this rename. Its tree is the same install, so use it.
      if (!fs.existsSync(path.join(target, RUNNER_FILENAME))) throw error;
    }

    deps.notify(`agent-relay: ${spec} ready (${Math.round((Date.now() - started) / 1000)}s).`);
    return target;
  } finally {
    // A no-op after a successful rename; on any failure it is what keeps a
    // dead staging tree from accumulating in the store.
    fs.rmSync(staging, { recursive: true, force: true });
  }
}

/**
 * Run the surface runner in a child process and collect its result.
 *
 * `node` is the interpreter because `node` is what performed the install: a
 * provisioned tree exists only if npm ran, and npm implies node. The compiled
 * binary cannot run these itself — see RUNNER_SOURCE.
 */
function runnerProcess(
  installRoot: string,
  args: readonly string[],
  io?: RelayCliIo
): Promise<{ code: number; stdout: string }> {
  const runner = path.join(installRoot, RUNNER_FILENAME);
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath.endsWith('node') ? process.execPath : 'node', [runner, ...args], {
      cwd: installRoot,
      // stdin inherited so an interactive product prompt still works.
      stdio: ['inherit', 'pipe', 'pipe'],
    });
    let stdout = '';
    child.stdout?.on('data', (chunk: Buffer) => {
      if (io) io.stdout(chunk);
      else stdout += chunk.toString('utf8');
    });
    child.stderr?.on('data', (chunk: Buffer) => io?.stderr(chunk));
    child.on('error', reject);
    child.on('close', (code) => resolve({ code: code ?? 1, stdout }));
  });
}

/**
 * The surface's declared command tree, read out of a provisioned tree.
 *
 * Only the declaration crosses the process boundary — `run` cannot, so the
 * returned surface's `run` delegates to another child process.
 */
export async function loadSurfaceFromStore(installRoot: string, specifier: string): Promise<RelayCliSurface> {
  const described = await runnerProcess(installRoot, ['describe', specifier]);
  if (described.code !== 0) {
    throw new SurfaceProvisionError(
      `The provisioned package tree at ${installRoot} could not describe ${specifier}.\n` +
        'Delete that directory and retry; it will be reinstalled.'
    );
  }
  const declaration = JSON.parse(described.stdout) as Omit<RelayCliSurface, 'run'>;
  return {
    ...declaration,
    run: async (argv, io) => {
      const result = await runnerProcess(installRoot, ['run', specifier, ...argv], io);
      return result.code;
    },
  };
}

/**
 * Turn a failed `npm install` into one actionable line.
 *
 * npm's own output is dozens of lines ending in a path to a debug log the user
 * of a standalone binary has no reason to read. What decides their next move is
 * the first error npm reported — `ENOTFOUND`, `E403`, `ETARGET` — so that is
 * what gets lifted out.
 */
export function describeInstallFailure(command: string, error: unknown): string {
  const code = (error as { code?: unknown } | undefined)?.code;
  if (code === 'ENOENT') {
    return `\`${command}\` is not on PATH.`;
  }
  if ((error as { killed?: boolean } | undefined)?.killed === true) {
    return `\`${command} install\` timed out after ${Math.round(INSTALL_TIMEOUT_MS / 60_000)} minutes.`;
  }
  const lines = String((error as { stderr?: unknown } | undefined)?.stderr ?? '')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .slice(0, 3);
  return lines.length > 0 ? redactCredentialValues(lines.join('\n')) : describeError(error);
}

/** The real installer: one `npm install` scoped to the staging directory. */
async function npmInstall(pkg: SurfacePackage, directory: string): Promise<void> {
  const command = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  try {
    await execFileAsync(
      command,
      ['install', `${pkg.name}@${pkg.range}`, '--no-audit', '--no-fund', '--loglevel=error'],
      {
        cwd: directory,
        timeout: INSTALL_TIMEOUT_MS,
        maxBuffer: INSTALL_MAX_BUFFER,
        // The update notifier writes to stderr and can outlive the install.
        env: { ...process.env, npm_config_update_notifier: 'false' },
      }
    );
  } catch (error) {
    throw new Error(describeInstallFailure(command, error), { cause: error });
  }
}
