/**
 * Generated by packages/telemetry/scripts/write-build-config.mjs.
 * The publish pipeline injects these values from GitHub repository variables.
 */
export const BUILD_POSTHOG_API_KEY = "";
export const BUILD_POSTHOG_HOST = "https://us.i.posthog.com";
